import type { SiteData } from "../types";

export const siteData: SiteData = {
  personal: {
    name: "Akbar Naim",
    siteTitle: "Akbar Naim",
    headlinePrefix: "The gear. ",
    headlineEmphasis: "The worlds.",
    headlineSuffix: "",
    bio: "Every kit is a door into a different part of life. Tools, notes, and experiences that shape how I explore, build, and create.",
    bagPeekHint: "Hover over a bag to peek inside.",
    aboutCta: {
      label: "About Me",
      href: "/about",
    },
    location: "Toronto, Canada",
    email: "aknaim@outlook.com",
    social: [
      {
        platform: "github",
        label: "GitHub",
        url: "https://github.com/aknaim",
        icon: "Github",
      },
      {
        platform: "linkedin",
        label: "LinkedIn",
        url: "https://linkedin.com/in/syed-naim",
        icon: "Linkedin",
      },
      {
        platform: "email",
        label: "Email",
        url: "mailto:hello@akN.com",
        icon: "Mail",
      },
    ],
  },

  navigation: [
    {
      id: "about",
      label: "About",
      href: "/about",
      external: false,
    },
  ],

  interests: [
    {
      id: "climbing",
      label: "Climbing",
      icon: "Mountain",
      status: "active",
      bagImage: "/images/hero/bag-climbing.jpg",
      peekImage: "/images/hero/peek-climbing.jpg",
      peekCaption: "Aggressive downturned shoes, harness, Edelrid Ohmega, and chalk bag.",
      workbenchNote: "Gym sessions, projects, and the next grade — logged one send at a time.",
      panelAnchor: "climbing",
      tagline: "Progress, lessons, and mountain days.",
      heroImage: "/images/hero/hero-climbing.jpg",
      tabs: [
        {
          id: "logbook",
          label: "Logbook",
          items: [
            { id: "c1", title: "Red River Gorge Trip", meta: "May 18, 2026", thumbnail: "/images/thumbs/rrg.jpg", linkUrl: "/journal/rrg" },
            { id: "c2", title: "First 5.12 Lead", meta: "Apr 22, 2026", thumbnail: "/images/thumbs/lead.jpg" },
            { id: "c3", title: "Training & Consistency", meta: "Mar 10, 2026", thumbnail: "/images/thumbs/training.jpg" }
          ]
        },
        {
          id: "routes",
          label: "Routes",
          items: [
            { id: "cr1", title: "Airfield (5.12a)", meta: "Red River Gorge • Sent" },
            { id: "cr2", title: "Amarillo Sunset (5.11b)", meta: "Red River Gorge • Flash" }
          ]
        },
        {
          id: "gear",
          label: "Gear",
          items: [
            { id: "cg1", title: "La Sportiva Solution Comp", meta: "Primary Shoe" },
            { id: "cg2", title: "Arc'teryx Chalk Bag", meta: "Chalk Bag" },
            { id: "cg3", title: "Black Diamond Momentum", meta: "Harness" },
            { id: "cg4", title: "Petzl Grigri", meta: "Belay Device" },
            { id: "cg5", title: "Edelrid Ohmega", meta: "Belay Assist" },
            { id: "cg6", title: "Mammut Neon 55", meta: "Backpack" },
            { id: "cg7", title: "Mammut Crag Sender", meta: "Helmet" },
            { id: "cg8", title: "Petzl Aria 2R RGB", meta: "Headlamp" },
            { id: "cg9", title: "Mammut 9.5 Crag We Care Classic", meta: "Rope" },
          ]
        },
        {
          id: "lessons",
          label: "Lessons",
          items: [
            { id: "cl1", title: "Dynamic Fall Braking", meta: "Lead Belaying Nuances" },
            { id: "cl2", title: "Rest Positioning Tactics", meta: "Endurance Management" }
          ]
        }
      ]
    },
    {
      id: "cooking",
      label: "Cooking",
      icon: "ChefHat",
      status: "active",
      bagImage: "/images/hero/bag-cooking.jpg",
      peekImage: "/images/hero/peek-cooking.jpg",
      peekCaption: "Infrared thermometer, cast-iron pans, and outdoor pizza deck tooling.",
      workbenchNote: "Outdoor pizza nights, dough experiments, and curry on rotation.",
      panelAnchor: "cooking",
      tagline: "Recipes, techniques, and delicious experiments.",
      heroImage: "/images/hero/hero-cooking.jpg",
      tabs: [
        {
          id: "recipes",
          label: "Recipes",
          items: [
            { id: "ck1", title: "Sourdough Pizza", meta: "May 5, 2026", thumbnail: "/images/thumbs/pizza.jpg" },
            { id: "ck2", title: "Handmade Pasta", meta: "Apr 27, 2026", thumbnail: "/images/thumbs/pasta.jpg" },
            { id: "ck3", title: "Fermented Hot Sauce", meta: "Apr 12, 2026", thumbnail: "/images/thumbs/sauce.jpg" }
          ]
        },
        {
          id: "journal",
          label: "Journal",
          items: [
            { id: "cj1", title: "Sourdough Starter Hydration Logs", meta: "Adjusting ambient fermentation variables" },
            { id: "cj2", title: "Neapolitan vs New York Profile", meta: "Baking floor temperature benchmarks" }
          ]
        },
        {
          id: "gear",
          label: "Gear",
          items: [
            { id: "ckg1", title: "Gozney Roccbox", meta: "High-Heat Outdoor Propane Oven" },
            { id: "ckg2", title: "Lodge 12-Inch Cast Iron Skillet", meta: "Heat Retention Baseline" }
          ]
        }
      ]
    },
    {
      id: "photography",
      label: "Photography",
      icon: "Camera",
      status: "dormant",
      bagImage: "/images/hero/bag-photography.jpg",
      peekImage: "/images/hero/peek-photography.jpg",
      peekCaption: "Sony full-frame body, manual prime lenses, and landscape filters.",
      workbenchNote: "Chasing light — primes, landscapes, and golden-hour alarms.",
      lastActive: "2024-10-01",
      panelAnchor: "photography",
      tagline: "Exposure, composition, and the frame that finally sticks.",
      heroImage: "/images/hero/hero-photography.jpg",
      tabs: [
        {
          id: "courses",
          label: "Courses",
          items: [
            {
              id: "phc1",
              title: "Digital Photography 1",
              meta: "PHOT 9037 · George Brown",
              linkUrl: "/photography",
            },
          ],
        },
        {
          id: "gear",
          label: "Gear",
          items: [
            { id: "phg1", title: "Sony A7 III", meta: "Full-frame body", linkUrl: "/photography" },
            {
              id: "phg2",
              title: "Tamron 28-200",
              meta: "Travel zoom",
              linkUrl: "/photography",
            },
          ],
        },
      ],
    },
    {
      id: "travel",
      label: "Travel",
      icon: "Plane",
      status: "active",
      bagImage: "/images/hero/bag-travel.jpg",
      peekImage: "/images/hero/peek-travel.jpg",
      peekCaption: "Camera, passport, and the kit for the next road.",
      workbenchNote: "Trip notes, galleries, and mapping the next slow road.",
      lastActive: "2024-07-01",
      panelAnchor: "travel",
      tagline: "Stories from places that shape perspective.",
      heroImage: "/images/hero/hero-travel.jpg",
      tabs: [
        {
          id: "stories",
          label: "Stories",
          items: [
            { id: "t1", title: "Amalfi Coast, Italy", meta: "Aug 5, 2025", thumbnail: "/images/thumbs/italy.jpg" },
            { id: "t2", title: "Patagonia Road Trip", meta: "Feb 10, 2025", thumbnail: "/images/thumbs/patagonia.jpg" },
            { id: "t3", title: "Japan in 3 Weeks", meta: "Apr 7, 2024", thumbnail: "/images/thumbs/japan.jpg" }
          ]
        },
        {
          id: "itineraries",
          label: "Itineraries",
          items: [
            { id: "ti1", title: "Kyoto Backstreets Route", meta: "Historical Architecture Focus" },
            { id: "ti2", title: "Torres del Paine W-Trek", meta: "Self-Supported Hiking Logistics" }
          ]
        },
        {
          id: "maps",
          label: "Maps",
          items: [
            { id: "tm1", title: "Custom Tokyo Coffee Log", meta: "Sparsed Google Maps Overlay" }
          ]
        }
      ]
    },
    {
      id: "woodworking",
      label: "Carpentry & Home Renovation",
      icon: "Hammer",
      status: "dormant",
      bagImage: "/images/hero/bag-woodworking.jpg",
      peekImage: "/images/hero/peek-woodworking.jpg",
      peekCaption: "Shop classes, home repairs, and the next cut that fits.",
      workbenchNote: "Shop skills, home repairs, and the next cut that fits.",
      lastActive: "2023-01-01",
      panelAnchor: "woodworking",
      tagline: "Shop skills and home repairs, one course at a time.",
      heroImage: "/images/hero/hero-woodworking.jpg",
      tabs: [
        {
          id: "courses",
          label: "Courses",
          items: [
            {
              id: "wc2",
              title: "Home Maintenance and Improvements: Basics",
              meta: "BLDG 9077 · George Brown",
              linkUrl: "/carpentry",
            },
            {
              id: "wc1",
              title: "Carpentry 1: Basic Woodworking",
              meta: "BLDG 9037 · George Brown",
              linkUrl: "/carpentry",
            },
          ],
        },
      ],
    },
    {
      id: "chess",
      label: "Chess",
      icon: "Swords",
      status: "active",
      bagImage: "/images/hero/bag-chess.jpg",
      peekImage: "/images/hero/peek-chess.jpg",
      peekCaption: "Board, clock, and a notebook of sharp lines.",
      workbenchNote: "Peak ratings and titled wins — sharp lines under the clock.",
      panelAnchor: "chess",
      tagline: "Peak ratings, peak games, and titled wins.",
      heroImage: "/images/hero/peek-chess.jpg",
      tabs: [
        {
          id: "peaks",
          label: "Peaks",
          items: [
            { id: "ch1", title: "Peak ratings", meta: "Chess.com & Lichess", linkUrl: "/chess#ratings" },
          ],
        },
        {
          id: "games",
          label: "Games",
          items: [
            { id: "ch2", title: "Titled wins", meta: "Unique opponents", linkUrl: "/chess#titled-wins" },
          ],
        },
        {
          id: "profiles",
          label: "Profiles",
          items: [
            {
              id: "ch4",
              title: "Chess.com · Aknaim",
              meta: "Main account",
              linkUrl: "https://www.chess.com/member/aknaim",
            },
            {
              id: "ch3",
              title: "Chess.com · ABlindChessPlayer",
              meta: "Profile",
              linkUrl: "https://www.chess.com/member/ABlindChessPlayer",
            },
            {
              id: "ch5",
              title: "Lichess · Aknaim",
              meta: "Profile",
              linkUrl: "https://lichess.org/@/Aknaim",
            },
          ],
        },
      ],
    },
    {
      id: "video-games",
      label: "Video Games",
      icon: "Gamepad2",
      status: "dormant",
      bagImage: "/images/hero/bag-video-games.jpg",
      peekImage: "/images/hero/peek-video-games.jpg",
      peekCaption: "Controllers, headset, and a queue that went quiet.",
      workbenchNote: "Favorites on the shelf — campaigns, co-op nights, and long queues.",
      panelAnchor: "video-games",
      tagline: "A shelf of favorites and matches worth remembering.",
      heroImage: "/images/hero/peek-video-games.jpg",
      tabs: [
        {
          id: "games",
          label: "Games",
          items: [
            {
              id: "vg1",
              title: "League of Legends",
              meta: "Expanded on shelf",
              linkUrl: "/video-games#shelf",
            },
            {
              id: "vg-shelf",
              title: "Shelf",
              meta: "RS3 + classics",
              linkUrl: "/video-games#shelf",
            },
          ],
        },
        {
          id: "league",
          label: "League",
          items: [
            {
              id: "vg2",
              title: "Season ranks",
              meta: "Diamond 5 peak era",
              linkUrl: "/video-games#shelf",
            },
          ],
        },
        {
          id: "profiles",
          label: "Profiles",
          items: [
            {
              id: "vg3",
              title: "aknaim",
              meta: "op.gg NA",
              linkUrl: "https://op.gg/lol/summoners/na/aknaim-NA1",
            },
            {
              id: "vg4",
              title: "kungfuscyther",
              meta: "op.gg NA",
              linkUrl: "https://op.gg/lol/summoners/na/kungfuscyther-NA1",
            },
            {
              id: "vg5",
              title: "aknaim",
              meta: "RS3 hiscores",
              linkUrl: "https://secure.runescape.com/m=hiscore/a=13/compare?user1=aknaim",
            },
          ],
        },
      ],
    },
  ],

  skills: [
    {
      id: "skill-typescript",
      name: "TypeScript",
      category: "language",
      proficiency: "expert",
      icon: "FileCode",
      relatedProjectIds: ["eng-portfolio", "eng-api-gateway"],
    },
    {
      id: "skill-python",
      name: "Python",
      category: "language",
      proficiency: "comfortable",
      icon: "FileCode",
      relatedProjectIds: ["eng-data-pipeline"],
    },
    {
      id: "skill-react",
      name: "React",
      category: "framework",
      proficiency: "expert",
      icon: "Layers",
      relatedProjectIds: ["eng-portfolio"],
    },
    {
      id: "skill-nextjs",
      name: "Next.js",
      category: "framework",
      proficiency: "expert",
      icon: "Layers",
      relatedProjectIds: ["eng-portfolio"],
    },
    {
      id: "skill-node",
      name: "Node.js",
      category: "platform",
      proficiency: "comfortable",
      icon: "Server",
      relatedProjectIds: ["eng-api-gateway"],
    },
    {
      id: "skill-postgres",
      name: "PostgreSQL",
      category: "tool",
      proficiency: "comfortable",
      icon: "Database",
      relatedProjectIds: ["eng-data-pipeline"],
    },
    {
      id: "skill-docker",
      name: "Docker",
      category: "tool",
      proficiency: "comfortable",
      icon: "Box",
      relatedProjectIds: ["eng-api-gateway"],
    },
    {
      id: "skill-aws",
      name: "AWS",
      category: "cloud",
      proficiency: "comfortable",
      icon: "Cloud",
      relatedProjectIds: ["eng-data-pipeline", "eng-api-gateway"],
    },
    {
      id: "skill-terraform",
      name: "Terraform",
      category: "cloud",
      proficiency: "learning",
      icon: "CloudCog",
      relatedProjectIds: ["eng-infra-automation"],
    },
    {
      id: "skill-system-design",
      name: "System Design",
      category: "soft",
      proficiency: "expert",
      icon: "Network",
      relatedProjectIds: [
        "eng-api-gateway",
        "eng-data-pipeline",
        "eng-infra-automation",
      ],
    },
  ],

  projects: [
    {
      id: "photo-landscape-01",
      category: "photography",
      tag: "landscapes",
      title: "Dawn over the ridge",
      date: "2024-05-12",
      description: "Golden-hour landscape from a weekend hike.",
      image: "/images/photography/landscape-01.jpg",
      href: "/photography/dawn-over-the-ridge",
      location: "Colorado, USA",
      alt: "Mountain ridge at sunrise with low clouds",
    },
    {
      id: "photo-urban-01",
      category: "photography",
      tag: "urban",
      title: "Alley geometry",
      date: "2024-03-08",
      description: "Urban lines and shadow play between buildings.",
      image: "/images/photography/urban-01.jpg",
      href: "/photography/alley-geometry",
      location: "Chicago, USA",
      alt: "Narrow urban alley with strong perspective lines",
    },
    {
      id: "photo-wildlife-01",
      category: "photography",
      tag: "wildlife",
      title: "Heron at the marsh",
      date: "2024-01-22",
      description: "Long lens capture at wetland preserve.",
      image: "/images/photography/wildlife-01.jpg",
      href: "/photography/heron-at-the-marsh",
      location: "Wisconsin, USA",
      alt: "Great blue heron standing in shallow marsh water",
    },
    {
      id: "climb-log-01",
      category: "climbing",
      tag: "logbook",
      title: "The Nose — partial ascent",
      date: "2024-04-18",
      description: "Multi-pitch trad day on iconic granite.",
      image: "/images/bento/climb-thumb.jpg",
      href: "/climbing/the-nose-partial",
      grade: "5.9 C2",
      location: "Yosemite, CA",
      routeName: "The Nose",
      highlight: false,
    },
    {
      id: "climb-log-02",
      category: "climbing",
      tag: "logbook",
      title: "Midnight Lightning",
      date: "2024-02-03",
      description: "Classic boulder problem in Camp 4.",
      image: "/images/bento/climb-thumb.jpg",
      href: "/climbing/midnight-lightning",
      grade: "V8",
      location: "Yosemite, CA",
      routeName: "Midnight Lightning",
      highlight: false,
    },
    {
      id: "climb-log-03",
      category: "climbing",
      tag: "logbook",
      title: "Epicenter",
      date: "2023-11-15",
      description: "Overhanging sport route with technical crux.",
      image: "/images/bento/climb-thumb.jpg",
      href: "/climbing/epicenter",
      grade: "5.12a",
      location: "Smith Rock, OR",
      routeName: "Epicenter",
      highlight: false,
    },
    {
      id: "climb-log-04",
      category: "climbing",
      tag: "logbook",
      title: "Outer Limits",
      date: "2023-09-02",
      description: "Steep pocket climbing on quality stone.",
      image: "/images/bento/climb-thumb.jpg",
      href: "/climbing/outer-limits",
      grade: "5.11d",
      location: "Red River Gorge, KY",
      routeName: "Outer Limits",
      highlight: false,
    },
    {
      id: "climb-highlight-01",
      category: "climbing",
      tag: "logbook",
      title: "Session Highlight — Pitch 3",
      date: "2024-04-18",
      description: "Clean send on the crux pitch before rain moved in.",
      image: "/images/bento/climb-thumb.jpg",
      href: "/climbing/session-highlight-pitch-3",
      grade: "5.10c",
      location: "Yosemite, CA",
      routeName: "The Nose — Pitch 3",
      highlight: true,
    },
    {
      id: "cook-sample-pasta",
      category: "cooking",
      tag: "savoury",
      title: "Sample · Garlic Butter Pasta",
      date: "2026-03-08",
      description: "Demo plate for layout — garlic, lemon, and parmesan.",
      image: "/images/hero/peek-cooking.jpg",
      href: "/cooking/sample-garlic-butter-pasta",
      thumbnail: "/images/hero/peek-cooking.jpg",
      recipeType: "Sample",
    },
    {
      id: "cook-placeholder-02",
      category: "cooking",
      tag: "sweet",
      title: "Kitchen notes",
      date: "—",
      description: "Courses, gear, and the dish that earns a remake.",
      image: "/images/hero/peek-cooking.jpg",
      href: "/cooking#courses",
      thumbnail: "/images/hero/peek-cooking.jpg",
      recipeType: "Notes",
    },
    {
      id: "travel-story-01",
      category: "travel",
      tag: "europe",
      title: "Amalfi coast by ferry",
      date: "2024-06-10",
      description: "Coastal towns, lemon groves, and late dinners in Positano.",
      image: "/images/travel/story-01.jpg",
      href: "/travel/amalfi-coast",
      thumbnail: "/images/travel/story-01.jpg",
      region: "Campania",
      country: "Italy",
    },
    {
      id: "travel-story-02",
      category: "travel",
      tag: "europe",
      title: "Kyoto temple walk",
      date: "2023-10-18",
      description: "Autumn maples and early-morning meditation paths.",
      image: "/images/travel/story-02.jpg",
      href: "/travel/kyoto-temple-walk",
      thumbnail: "/images/travel/story-02.jpg",
      region: "Kansai",
      country: "Japan",
    },
    {
      id: "travel-story-03",
      category: "travel",
      tag: "asia",
      title: "Hanoi street food circuit",
      date: "2023-07-04",
      description: "Pho, bún chả, and coffee on plastic stools.",
      image: "/images/travel/story-03.jpg",
      href: "/travel/hanoi-street-food",
      thumbnail: "/images/travel/story-03.jpg",
      region: "Red River Delta",
      country: "Vietnam",
    },
    {
      id: "travel-story-04",
      category: "travel",
      tag: "europe",
      title: "Iceland ring road — segment 3",
      date: "2022-08-22",
      description: "Waterfalls, black sand, and midnight sun drives.",
      image: "/images/travel/story-04.jpg",
      href: "/travel/iceland-ring-road",
      thumbnail: "/images/travel/story-04.jpg",
      region: "South Coast",
      country: "Iceland",
    },
    {
      id: "travel-map-italy",
      category: "travel",
      tag: "europe",
      title: "Italy — travel map",
      date: "2024-06-10",
      description: "Static map visual highlighting coastal route.",
      image: "/images/travel/italy-map.jpg",
      href: "/travel/italy-map",
      thumbnail: "/images/travel/italy-map.jpg",
      region: "Italy",
      country: "Italy",
    },
    {
      id: "wood-project-01",
      category: "woodworking",
      tag: "projects",
      title: "Walnut dining table",
      date: "2024-01-10",
      description: "Breadboard ends, hand-cut joinery, oil finish.",
      image: "/images/woodworking/featured-project.jpg",
      href: "/woodworking/walnut-dining-table",
      featured: true,
      material: "American walnut",
    },
    {
      id: "wood-project-02",
      category: "woodworking",
      tag: "projects",
      title: "Maple wall shelf",
      date: "2023-09-14",
      description: "Floating shelf with concealed brass pins.",
      image: "/images/woodworking/featured-project.jpg",
      href: "/woodworking/maple-wall-shelf",
      featured: false,
      material: "Hard maple",
    },
    {
      id: "wood-project-03",
      category: "woodworking",
      tag: "projects",
      title: "Cherry keepsake box",
      date: "2023-05-02",
      description: "Dovetail corners and suede-lined interior.",
      image: "/images/woodworking/featured-project.jpg",
      href: "/woodworking/cherry-keepsake-box",
      featured: false,
      material: "Cherry",
    },
    {
      id: "wood-project-04",
      category: "woodworking",
      tag: "projects",
      title: "Ash workbench top",
      date: "2022-11-28",
      description: "Laminated top with dog holes and vise retrofit.",
      image: "/images/woodworking/featured-project.jpg",
      href: "/woodworking/ash-workbench-top",
      featured: false,
      material: "Ash",
    },
  ],

  sectionTabs: {
    photography: [
      { id: "all", label: "ALL" },
      { id: "landscapes", label: "LANDSCAPES" },
      { id: "urban", label: "URBAN" },
      { id: "wildlife", label: "WILDLIFE" },
    ],
    climbing: [
      { id: "logbook", label: "LOGBOOK" },
      { id: "routes", label: "ROUTES" },
      { id: "lessons", label: "LESSONS" },
      { id: "gear", label: "GEAR" },
    ],
    cooking: [
      { id: "all", label: "ALL" },
      { id: "savoury", label: "SAVOURY" },
      { id: "sweet", label: "SWEET" },
    ],
    travel: [
      { id: "all", label: "ALL" },
      { id: "europe", label: "EUROPE" },
      { id: "asia", label: "ASIA" },
    ],
    woodworking: [
      { id: "projects", label: "PROJECTS" },
      { id: "tools", label: "TOOLS" },
      { id: "lessons", label: "LESSONS" },
    ],
    chess: [
      { id: "peaks", label: "PEAKS" },
      { id: "games", label: "GAMES" },
      { id: "profiles", label: "PROFILES" },
    ],
    "video-games": [
      { id: "games", label: "GAMES" },
      { id: "league", label: "LEAGUE" },
      { id: "profiles", label: "PROFILES" },
    ],
  },
};
