import type { TitledWin } from "./types";

/** Generated by scripts/scan-chess-titled-wins.mjs — re-run to refresh. */
export const TITLED_WINS: TitledWin[] = [
  {
    "id": "chesscom-ablind-34e745ec-0312-11ed-9220-78ac4409ff3c",
    "accountId": "chesscom-ablind",
    "opponent": "cardenasjunior64",
    "title": "IM",
    "url": "https://www.chess.com/game/live/51500358803",
    "timeControl": "blitz",
    "playedAt": "2022-07-14"
  },
  {
    "id": "chesscom-aknaim-10a3483d-2d28-11eb-ad12-c1085c010001",
    "accountId": "chesscom-aknaim",
    "opponent": "MyoNaing",
    "title": "IM",
    "url": "https://www.chess.com/game/live/5801055892",
    "timeControl": "bullet",
    "playedAt": "2020-11-23"
  },
  {
    "id": "chesscom-aknaim-ee8e660a-e0f2-11dd-8000-000000010001",
    "accountId": "chesscom-aknaim",
    "opponent": "Xena1911",
    "title": "IM",
    "url": "https://www.chess.com/game/live/381398977",
    "timeControl": "bullet",
    "playedAt": "2012-10-19"
  },
  {
    "id": "chesscom-aknaim-fa658822-22f2-11eb-b5fd-c1085c010001",
    "accountId": "chesscom-aknaim",
    "opponent": "guinero68",
    "title": "FM",
    "url": "https://www.chess.com/game/live/5716548957",
    "timeControl": "bullet",
    "playedAt": "2020-11-10"
  },
  {
    "id": "chesscom-aknaim-e2aa479c-1bdb-11eb-9e4d-c1085c010001",
    "accountId": "chesscom-aknaim",
    "opponent": "Jagrr",
    "title": "FM",
    "url": "https://www.chess.com/game/live/5666700028",
    "timeControl": "bullet",
    "playedAt": "2020-11-01"
  },
  {
    "id": "chesscom-aknaim-b811a1a8-5382-11dd-8000-000000010001",
    "accountId": "chesscom-aknaim",
    "opponent": "TheMagician",
    "title": "FM",
    "url": "https://www.chess.com/game/live/132578036",
    "timeControl": "bullet",
    "playedAt": "2011-05-23"
  },
  {
    "id": "lichess-aknaim-HEjzmBsd",
    "accountId": "lichess-aknaim",
    "opponent": "behappii",
    "title": "WFM",
    "url": "https://lichess.org/HEjzmBsd",
    "timeControl": "bullet",
    "playedAt": "2018-12-02"
  },
  {
    "id": "chesscom-aknaim-234a4eb2-58fd-11e4-8000-000000010001",
    "accountId": "chesscom-aknaim",
    "opponent": "vignesh2809",
    "title": "WFM",
    "url": "https://www.chess.com/game/live/3294735125",
    "timeControl": "bullet",
    "playedAt": "2018-12-15"
  },
  {
    "id": "chesscom-aknaim-e1f34fad-9d91-11eb-954e-536974010001",
    "accountId": "chesscom-aknaim",
    "opponent": "AndrewHoy",
    "title": "NM",
    "url": "https://www.chess.com/game/live/12192421617",
    "timeControl": "blitz",
    "playedAt": "2021-04-15"
  },
  {
    "id": "chesscom-aknaim-0cfd2672-3a9f-11eb-afcf-0069e4010001",
    "accountId": "chesscom-aknaim",
    "opponent": "claudioa",
    "title": "NM",
    "url": "https://www.chess.com/game/live/5929855531",
    "timeControl": "bullet",
    "playedAt": "2020-12-10"
  },
  {
    "id": "chesscom-ablind-f413dcc7-133c-11eb-bae7-c1085c010001",
    "accountId": "chesscom-ablind",
    "opponent": "claudioa",
    "title": "NM",
    "url": "https://www.chess.com/game/live/5612757363",
    "timeControl": "bullet",
    "playedAt": "2020-10-21"
  },
  {
    "id": "chesscom-aknaim-7f51520a-62c8-11dd-8000-000000010001",
    "accountId": "chesscom-aknaim",
    "opponent": "cldng",
    "title": "NM",
    "url": "https://www.chess.com/game/live/159445825",
    "timeControl": "bullet",
    "playedAt": "2011-08-03"
  },
  {
    "id": "chesscom-aknaim-7540bc7c-21eb-11eb-b5fd-c1085c010001",
    "accountId": "chesscom-aknaim",
    "opponent": "DisgustingSasquatch",
    "title": "NM",
    "url": "https://www.chess.com/game/live/5708646355",
    "timeControl": "bullet",
    "playedAt": "2020-11-08"
  },
  {
    "id": "chesscom-aknaim-1b148747-3cfb-11eb-99d4-0069e4010001",
    "accountId": "chesscom-aknaim",
    "opponent": "Dres1",
    "title": "NM",
    "url": "https://www.chess.com/game/live/5953606007",
    "timeControl": "bullet",
    "playedAt": "2020-12-13"
  },
  {
    "id": "lichess-aknaim-oEMhdEmu",
    "accountId": "lichess-aknaim",
    "opponent": "eugeniusjr",
    "title": "NM",
    "url": "https://lichess.org/oEMhdEmu",
    "timeControl": "bullet",
    "playedAt": "2022-05-14"
  },
  {
    "id": "lichess-aknaim-j7EaS22S",
    "accountId": "lichess-aknaim",
    "opponent": "FleetWalker",
    "title": "NM",
    "url": "https://lichess.org/j7EaS22S",
    "timeControl": "blitz",
    "playedAt": "2021-10-10"
  },
  {
    "id": "chesscom-aknaim-89123fd0-4e1b-11eb-9c8f-0069e4010001",
    "accountId": "chesscom-aknaim",
    "opponent": "kallerotmg",
    "title": "NM",
    "url": "https://www.chess.com/game/live/6136204668",
    "timeControl": "bullet",
    "playedAt": "2021-01-03"
  },
  {
    "id": "chesscom-aknaim-76bebe0d-2b97-11eb-ac28-c1085c010001",
    "accountId": "chesscom-aknaim",
    "opponent": "kkpanu9",
    "title": "NM",
    "url": "https://www.chess.com/game/live/5787389613",
    "timeControl": "bullet",
    "playedAt": "2020-11-21"
  },
  {
    "id": "chesscom-aknaim-ce45580a-49a7-11dd-8000-000000010001",
    "accountId": "chesscom-aknaim",
    "opponent": "s2004k1993",
    "title": "NM",
    "url": "https://www.chess.com/game/live/115240705",
    "timeControl": "bullet",
    "playedAt": "2011-04-04"
  },
  {
    "id": "chesscom-aknaim-a05ee30a-3d1a-11dd-8000-000000010001",
    "accountId": "chesscom-aknaim",
    "opponent": "samuraichessman",
    "title": "NM",
    "url": "https://www.chess.com/game/live/93159905",
    "timeControl": "bullet",
    "playedAt": "2011-01-31"
  },
  {
    "id": "chesscom-aknaim-2e85deee-31f4-11de-8000-000000010001",
    "accountId": "chesscom-aknaim",
    "opponent": "steelysteam",
    "title": "NM",
    "url": "https://www.chess.com/game/live/523904283",
    "timeControl": "bullet",
    "playedAt": "2013-05-27"
  },
  {
    "id": "chesscom-aknaim-d9e3ef17-18d0-11eb-ae08-c1085c010001",
    "accountId": "chesscom-aknaim",
    "opponent": "tactwiz",
    "title": "NM",
    "url": "https://www.chess.com/game/live/5646646196",
    "timeControl": "bullet",
    "playedAt": "2020-10-28"
  },
  {
    "id": "chesscom-aknaim-7d66e041-fe52-11ec-9220-78ac4409ff3c",
    "accountId": "chesscom-aknaim",
    "opponent": "WalkingHobbit",
    "title": "NM",
    "url": "https://www.chess.com/game/live/50977832147",
    "timeControl": "blitz",
    "playedAt": "2022-07-08"
  },
  {
    "id": "chesscom-aknaim-9dc8b6af-7103-11ec-995d-78ac4409ff3c",
    "accountId": "chesscom-aknaim",
    "opponent": "White_Bull",
    "title": "NM",
    "url": "https://www.chess.com/game/live/35441179409",
    "timeControl": "blitz",
    "playedAt": "2022-01-09"
  },
  {
    "id": "lichess-aknaim-kfNyeGsI",
    "accountId": "lichess-aknaim",
    "opponent": "EnDsOnLiMaRR",
    "title": "CM",
    "url": "https://lichess.org/kfNyeGsI",
    "timeControl": "bullet",
    "playedAt": "2020-01-18"
  },
  {
    "id": "chesscom-ablind-547dca0a-9273-11f1-997b-11af3501000f",
    "accountId": "chesscom-ablind",
    "opponent": "MNHBHUIYAN77",
    "title": "CM",
    "url": "https://www.chess.com/game/live/172661663236",
    "timeControl": "blitz",
    "playedAt": "2026-08-07"
  },
  {
    "id": "chesscom-aknaim-69aee316-4347-11eb-8649-0069e4010001",
    "accountId": "chesscom-aknaim",
    "opponent": "Practical-Play",
    "title": "CM",
    "url": "https://www.chess.com/game/live/6019228007",
    "timeControl": "bullet",
    "playedAt": "2020-12-21"
  }
];
